### ISSUE TITLE
ImportError: No module named 'coverage'

### ISSUE THREAD

**Issue by charlesakio** [charlesakio/student_job#13]
``` python
▶ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/charlesjavelona/.virtualenvs/student_job/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/charlesjavelona/.virtualenvs/student_job/lib/python3.4/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/charlesjavelona/.virtualenvs/student_job/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/charlesjavelona/.virtualenvs/student_job/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/charlesjavelona/.virtualenvs/student_job/lib/python3.4/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/Users/charlesjavelona/.virtualenvs/student_job/lib/python3.4/importlib/__init__.py", line 104, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2201, in _find_and_load_unlocked
ImportError: No module named 'coverage'
```

# Steps to Reproduce:
- On terminal, go to student_job root folder 
- Type ``` python manage.py runserver or makemigrations```
- Press enter
- Observe

**Comment by charlesakio** [comment]
Please take a look at this soon.

**Comment by juliosueiras** [comment]
Fix:
```shell
$ pip install -r requirements.txt
```
you forgot to install coverage (is in the requirements.txt
